### ISSUE TITLE
RSS feed is broken, as seen on planet.clojure.in

### ISSUE THREAD

**Issue by thegeez** [ingesolvoll/ingesolvoll.github.io#1]
Your blog is on http://planet.clojure.in/ but the links in your RSS feed are broken. Clicking on your blogpost leads to a "yourdomain.com" link, instead of to "ingesolvoll.github.io".

I think you need to adjust this setting: 
https://github.com/ingesolvoll/ingesolvoll.github.io/blob/5d4d68790b98c6c80013aadd676022fc9e570d0b/_config.yml#L14

**Comment by ingesolvoll** [comment]
Wow, thanks. I'll fix that ASAP.

Did not know about your blog, will add it to my list :)
